# =============================================================================
#           *** ملف التشغيل التلقائي (v1.2 - اختبار تيليجرام) ***
#
#  (هذا الملف يتجاهل API الألعاب ويختبر فقط تيليجرام)
# =============================================================================

name: Daily Games Bot (v1.2 - Telegram Test)

on:
  workflow_dispatch: # (سنقوم بالاختبار اليدوي فقط)

jobs:
  run-telegram-test:
    runs-on: ubuntu-latest
    env:
      # (هذا الاختبار يحتاج فقط إلى هذين المفتاحين)
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install requests
      - name: Run Python Script (Telegram Test)
        # (سيقوم بتشغيل "كود الاختبار" الجديد)
        run: python games_poster_test.py

