# =============================================================================
#           *** ملف التشغيل التلقائي (v1.0 - بوت الألعاب) ***
#
#  (ينشر 6 مرات يومياً، كل 4 ساعات)
# =============================================================================

name: Daily Games Bot (v1.0)

on:
  schedule:
    # (الجدول: 6 مرات يومياً - كل 4 ساعات)
    # (UTC: 00, 04, 08, 12, 16, 20)
    # (توقيت بغداد: 3ص, 7ص, 11ص, 3ظ, 7م, 11م)
    - cron: '0 0,4,8,12,16,20 * * *'

  # هذا يسمح لنا بالاختبار اليدوي
  workflow_dispatch:

jobs:
  run-daily-poster:
    runs-on: ubuntu-latest
    env:
      # (المفاتيح السرية الثلاثة التي أضفتها للمستودع الجديد)
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      GAMES_API_KEY: ${{ secrets.GAMES_API_KEY }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install requests
      - name: Run Python Script
        run: python games_poster.py

