# =============================================================================
#           *** ملف التشغيل التلقائي (v1.1 - بوت الألعاب) ***
#
#  (نسخة الاختبار - بدون ترجمة)
# =============================================================================

name: Daily Games Bot (v1.1 - No Translation)

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  run-daily-poster:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      GAMES_API_KEY: ${{ secrets.GAMES_API_KEY }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install requests
      - name: Run Python Script
        # (سيقوم بتشغيل الكود الجديد v1.1)
        run: python games_poster.py

